### ISSUE TITLE
Activating the toy from the map

### ISSUE THREAD

**Issue by robhalsey** [p3lim-wow/InteractiveWormholes#1]
Hey there, thanks for making this addon, I love the concept.  Unfortunately, I don't see any clickable portals on my map for any of the zones that I have a wormhole generator for.  Any suggestions?

**Comment by p3lim** [comment]
Did you use and talk to the wormhole?

**Comment by robhalsey** [comment]
Looks like I was just dumb and didn't realize that you had to click on the actual wormhole toy first to activate it, then select the location.  I was assuming that the addon simply added all of the known the wormhole/teleporter locations on the maps, then would allow you to click on one of them, which would activate the appropriate generator/teleporter toy from your collection without having the actually access the toy collection or place it on a action bar.  Would it be possible to have the addon do this since it would make teleporting even easier, and save bar space and/or time accessing the toy collection?  Again, very cool addon even the way it is, thanks for the hard work on it!  :-)

**Comment by p3lim** [comment]
I could look into it, no promises though.

**Comment by robhalsey** [comment]
Thanks for looking into this, I think that kind of functionality would definitely make the addon an essential one for all engineers!

**Comment by p3lim** [comment]
Considering the amount of buttons that would be added to support all the spells/toys, and how cluttered the map frame is by other addons, not to mention that these buttons needs to be secure, I don't see this as a feasible feature.
You're better off using OPie or something to group these spells/toys.
