### ISSUE TITLE
Dark Iron dwarf Mole Machine not working

### ISSUE THREAD

**Issue by Bexan** [p3lim-wow/InteractiveWormholes#13]
Using Version 80100.10-Release

Clicking a destination for the Mole Machine only closes the map and takes me nowhere.
This is the Error message wow provides

Message: ...s\InteractiveWormholes\modules\UnderbellyPortals.lua:16: attempt to compare number with nil
Time: Sun Jan 20 14:54:23 2019
Count: 12
Stack: ...s\InteractiveWormholes\modules\UnderbellyPortals.lua:16: attempt to compare number with nil
[C]: ?
...s\InteractiveWormholes\modules\UnderbellyPortals.lua:16: in function `callback'
Interface\AddOns\InteractiveWormholes\addon.lua:130: in function <Interface\AddOns\InteractiveWormholes\addon.lua:116>

Locals:

**Comment by Bexan** [comment]
Tried it, still same result, just looks like this when I try using it, no error message pops up at all now

https://gyazo.com/4841d2ed1111d63249b35d578c4a19e0

**Comment by p3lim** [comment]
I see the issue now, I'll get a fix out shortly.

**Comment by p3lim** [comment]
Seems there is still some weird issue with this.

**Comment by p3lim** [comment]
So, the issue I'm seeing (this is very technical, but I'm dumping this info regardless) is when I "hide" the default gossip window (by unregistering the event that would normally show it) I lose track of the NPC it exists for, so when the second gossip window shows, it has no NPC correlated with it, thus none of the zones gets clicked (and this is why you'd see the gossip window when you click the zone).

**Comment by p3lim** [comment]
Found a (slightly hacky) solution:
https://github.com/p3lim-wow/InteractiveWormholes/commit/d50f65e931c85b32bb4a94ac36a52fab8b77f42d
https://github.com/p3lim-wow/InteractiveWormholes/commit/f3510e90ab837ce1f139f9bb8f7b8b08fe8a808b

**Comment by Bexan** [comment]
Gonna give it a go when I'm back at my pc, thanks for the help!

**Comment by Bexan** [comment]
Sorry, dissapeared from wow for a bit. Back now and tried the changes to addon.lua and the molemachine module but still getting the same issue, it closes out without sending me anywhere. 
The only difference I found now is that if I interact with the mole machine quickly again after attempting to go somewhere, it'll just open the normal in game map, without any clickable wormhole icons : / Closing the map and interacting with the wormhole again gets me the map with the interactable icons, but still no functionality.
