### ISSUE TITLE
Small icon issue

### ISSUE THREAD

**Issue by smalliconissue** [p3lim-wow/InteractiveWormholes#17]
![KlYmUQT](https://user-images.githubusercontent.com/52434336/60476834-47e90300-9c3a-11e9-8be4-4e69209c76fb.jpg)
![fJxdyNe](https://user-images.githubusercontent.com/52434336/60476835-47e90300-9c3a-11e9-93f3-c85afd0d8774.jpg)

The icons are very small, I disabled a bunch of addons and was able to narrow it down to Zygor's causing the issue, I've also had issues with Zygor's messing with the Pa'ku totems addon so it might be something that you are unable to deal with.

**Comment by p3lim** [comment]
Sounds like an incompatibility between Zygor and [HereBeDragons](https://github.com/Nevcairiel/HereBeDragons) - the library used to interact with the map, which the Pa'ku addon also uses.
Try asking nev about this, I can't do much about it.
