### ISSUE TITLE
Foothold error

### ISSUE THREAD

**Issue by Saxayone** [p3lim-wow/InteractiveWormholes#20]
Trying to select a Foothold gives the error:

3x InteractiveWormholes\marker.lua:14: attempt to call global 'SelectGossipOption' (a nil value)
[string "@InteractiveWormholes\marker.lua"]:14: in function <InteractiveWormholes\marker.lua:12>

Locals:
self = <unnamed> {
 0 = <userdata>
 SetNormalAtlas = <function> defined @InteractiveWormholes\marker.lua:111
 Highlight = <unnamed> {
 }
 Arrow = <unnamed> {
 }
 Enable = <function> defined @InteractiveWormholes\marker.lua:176
 GetTitle = <function> defined @InteractiveWormholes\marker.lua:86
 SetSize = <function> defined @InteractiveWormholes\marker.lua:134
 Quest = <unnamed> {
 }
 Texture = <unnamed> {
 }
 DisableArrow = <function> defined @InteractiveWormholes\marker.lua:161
 disabled = false
 SetHighlightAtlas = <function> defined @InteractiveWormholes\marker.lua:122
 SetSource = <function> defined @InteractiveWormholes\marker.lua:153
 SetDescription = <function> defined @InteractiveWormholes\marker.lua:95
 MarkQuest = <function> defined @InteractiveWormholes\marker.lua:143
 GetDescription = <function> defined @InteractiveWormholes\marker.lua:102
 IsEnabled = <function> defined @InteractiveWormholes\marker.lua:184
 Pin = <function> defined @InteractiveWormholes\marker.lua:63
 SetTitle = <function> defined @InteractiveWormholes\marker.lua:79
 Disable = <function> defined @InteractiveWormholes\marker.lua:168
}
(*temporary) = nil
(*temporary) = 2
(*temporary) = "attempt to call global 'SelectGossipOption' (a nil value)"

**Comment by p3lim** [comment]
Will get this fixed as soon as I can test the fix myself, the authentication servers are not letting me log in.
