### ISSUE TITLE
Talking to a wormhole prevents opening NPC dialogs in combat until reload

### ISSUE THREAD

**Issue by kaldonir** [p3lim-wow/InteractiveWormholes#22]
**Describe the bug**
After talking to the Shadowlands Wormhole, NPC dialogs won't open in combat, and instead produce a chat message "Interface action failed because of an AddOn". A similar issue can be observed when talking to the Shadowlands Wormhole while in combat. `/reload` temporarily fixes the issue. This happens when InteractiveWormholes is the only active addon. 

**How to reproduce**
1. Talk to Shadowlands Wormhole
2. Get in combat
3. While in combat talk to an NPC

**What did you expect?**
The AddOn should not prevent opening NPC dialogs in combat.

**Taint log**
Taint log produced with `/console taintLog 2`:
[taint.log](https://github.com/p3lim-wow/InteractiveWormholes/files/5767245/taint.log.txt)

**Comment by p3lim** [comment]
Please try the latest version, seems to work fine with my testing.
You can find a packaged alpha version from the build artifacts:
https://github.com/p3lim-wow/InteractiveWormholes/actions/runs/462566580

**Comment by kaldonir** [comment]
Yes, this fixed the issue. Thanks for the quick help!
