### ISSUE TITLE
Is Mole OK?

### ISSUE THREAD

**Issue by Sooleawa** [p3lim-wow/InteractiveWormholes#24]
**Describe the bug**

I also need to 2xclick every time. Like someone who wrote other ticket.
I mostly use the addon for the Dark Iron Mole.
After the second click, it transports me to very different places it should.
(close this if unnecessary)

**How to reproduce**

Use Mole Machine, be confused where i am.

**What did you expect?**

To be at the correct place.
So far i used it to get to Un'goro crater multiple times,   it always puts me in Stormwind
Now i tested it again, clicked on Hinterlands,  i got ported to Icecrown.

**Comment by p3lim** [comment]
Duplicate of #23.
