### ISSUE TITLE
About the Mole Machine

### ISSUE THREAD

**Issue by Jkizis74** [p3lim-wow/InteractiveWormholes#25]
I know i'ts right in front of me somewhere but cant find it. the config for the addon. I am going nuts tryign to locate it. sorry for wasting someone's time. 
Ok, where do I turn off mole machine locations? as a light draeni the mole machine is not an option. AS an engineer I love the addon though. Just want to turn off all the map icons of it. I checked the interface/addons. tried different commands. figured quickest way now was just to ask.

**Comment by p3lim** [comment]
The locations should only ever show up if you're interacting with the mole machine, they should never show up on the map otherwise.

**Comment by Jkizis74** [comment]
Handy note package. when I open up the list... HandyNotes - Mole Machine.
gtg. Thanks for getting back to me too.
