### ISSUE TITLE
Zereth Mortis wormhole

### ISSUE THREAD

**Issue by JakobSchroeder** [p3lim-wow/InteractiveWormholes#33]
There's a new wormhole location for the Shadowlands generator at 45, 55 in ZM (inside the FT in forge of aFTerlives on the map). Unlock seems to be from doing the 150 fragment WM quest given to you in Oribos.

**Comment by p3lim** [comment]
Which quest exactly?

**Comment by JakobSchroeder** [comment]
https://www.wowhead.com/quest=65649/a-new-deal

**Comment by p3lim** [comment]
Thanks, yeah a relog was necessary.

**Comment by p3lim** [comment]
It's also account-wide!
