### ISSUE TITLE
bugs with the addon Leatrix maps

### ISSUE THREAD

**Issue by ZehelFenris** [p3lim-wow/InteractiveWormholes#37]
When using this addon with [Leatrix maps](https://www.curseforge.com/wow/addons/leatrix-maps) it shows both the normal gossip options and the map.

If i disable Leatrix maps then it only shows the portal locations on the map

![unknown](https://user-images.githubusercontent.com/43239740/194777376-9ad5d436-8a9e-42c0-bd9b-63df8af7fb04.png)

**Comment by p3lim** [comment]
After a quick scan through Leatrix Maps I found nothing that would interfere with IW, so I'm unsure what's causing this.

Are you sure you're displaying lua errors? `/console scriptErrors 1`

**Comment by ZehelFenris** [comment]
just tried to do the /console scriptErrors 1 and then use both the shadowlands and the draenor wormholes but theres no lua errors

**Comment by p3lim** [comment]
Installed Leatrix Maps and I'm unable to replicate this issue. What are your settings for Leatrix?

**Comment by ZehelFenris** [comment]
![unknown](https://user-images.githubusercontent.com/43239740/194778724-c4b5253b-606f-497a-b925-f770aaf2727d.png)

**Comment by p3lim** [comment]
Still can't replicate it. Can you try with only Leatrix and IW enabled? If that still doesn't work, is there anything mentioned in `wow/_retail_/logs/taint.log`?

**Comment by ZehelFenris** [comment]
i still have the problem with only those two enabled and i dont have a taint.log

**Comment by ZehelFenris** [comment]
I hope so would be a shame if i was to find a new map addon :P
