### ISSUE TITLE
Add Support for Underground Option for Wormhole Generator: Northrend

### ISSUE THREAD

**Issue by xShojirox** [p3lim-wow/InteractiveWormholes#4]
I love the addon, but from what I can tell there is no support for the rarely seen Underground option when using the Wormhole Generator: Northrend.  Currently I always shift click on the portals to double check, as I found in the code that opens the default menu, but it would be really cool to be able to have the portal show up in Dalaran when the Underground option appears.

I know this is something that might be difficult to test given how rarely it shows up.

**Comment by p3lim** [comment]
Should be easy enough to add, I just need coordinates for it.

**Comment by xShojirox** [comment]
The coordinates on the Northrend map would just be where Dalaran is. 

http://www.wowhead.com/item=48933/wormhole-generator-northrend#comments:id=764467

The 6th option for Underground rarely appears, but when it does and you choose it, it sends you into the pit under the grate in the horde side of Dalaran where a vendor, [Kaye Toogie](http://www.wowhead.com/npc=35826/kaye-toogie), sits. It is the only way to get to her and she sells Mechanical Dragonling schematics, and she is even the only way to get the Arcanite Dragonling schematic.

**Comment by p3lim** [comment]
Just logged on and got the option 👍 
Will be adding it to the next version with accurate coordinates.

**Comment by p3lim** [comment]
Pushed new version, should be available for download soon.
