### ISSUE TITLE
lua error

### ISSUE THREAD

**Issue by matton300** [p3lim-wow/InteractiveWormholes#42]
Hi, i got this error today while opening edit mode.

1x [ADDON_ACTION_FORBIDDEN] AddOn 'InteractiveWormholes' tried to call the protected function 'ClearTarget()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `ClearTarget'
[string "@Interface/FrameXML/EditModeManager.lua"]:1496: in function `ResetTargetAndFocus'
[string "@Interface/FrameXML/EditModeManager.lua"]:1479: in function `OnEditModeExit'
[string "@Interface/FrameXML/EditModeManager.lua"]:185: in function `ExitEditMode'
[string "@Interface/FrameXML/EditModeManager.lua"]:205: in function <Interface/FrameXML/EditModeManager.lua:203>
[string "=[C]"]: in function `Hide'
[string "@Interface/FrameXML/UIParent.lua"]:2828: in function `SetUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2859: in function `MoveUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2890: in function `HideUIPanel'
[string "@Interface/FrameXML/UIParent.lua"]:2556: in function <Interface/FrameXML/UIParent.lua:2548>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/FrameXML/UIParent.lua"]:3170: in function `HideUIPanel'
[string "@Interface/FrameXML/EditModeManager.lua"]:122: in function `onCloseCallback'
[string "@Interface/SharedXML/SharedUIPanelTemplates.lua"]:127: in function <Interface/SharedXML/SharedUIPanelTemplates.lua:122>
[string "=[C]"]: in function `Click'
[string "@Interface/FrameXML/UIParent.lua"]:3980: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

**Comment by p3lim** [comment]
Am aware of this issue, but unless I have a 100% reproducible way of triggering the error there's not much I can do to fix it.

**Comment by p3lim** [comment]
Found a reproducible way, and the cause is from the addon opening the map, which is kind of crucial for its functionality. Just /reload after using the edit mode like every other addon author is going to say whenever a taint occurs from it.

**Comment by p3lim** [comment]
Fixed as of build 47067 :tada:
