### ISSUE TITLE
Add support for Manapoof Teleports

### ISSUE THREAD

**Issue by Taizunz** [p3lim-wow/InteractiveWormholes#43]
**Describe the solution you'd like**
For the Battle Pet Dungeon Teleport NPC "Manapoof" to be supported by this addon.
The three different Manapoof NPCs:
In Dazar'alor: https://www.wowhead.com/npc=147642/manapoof
In Boralus: https://www.wowhead.com/npc=147666/manapoof
In Legion Dalaran: https://www.wowhead.com/npc=121602/manapoof

**Describe alternatives you've considered**
None.

**Comment by p3lim** [comment]
Was not aware of this one, seems pretty cool, but I have not done any battle pet dungeons so I'll need you to gather some information for me.

While talking to this NPC, run this command and give me the output, for each of the NPCs:
```
/run for i,o in next,C_GossipInfo.GetOptions() do print(i,'-',o.gossipOptionID,o.name) end
```
If the output is the same in Dazar, Boralus and Dalaran then you only need to reply with the output from one of them.


After gathering this, use each of the teleports then as soon as you finish the loading screen, without moving an inch, run this command and give me the output of each:
```
/run m=C_Map.GetBestMapForUnit('player');p=C_Map.GetPlayerMapPosition(m, 'player') or CreateVector2D(0,0);print(m,p:GetXY())
```

Screenshots of the chat output is fine.

**Comment by Taizunz** [comment]
Every Manapoof has the same gossip option IDs:
```
1 - 47007 Would you please send me to the Wailing Caverns?
2 - 47008 Would you please send me to the Deadmines? 
3 - 47009 Would you please send me to Gnomeregan? 
4 - 47010 Would you please send me to Stratholme? 
5 - 47011 I'm ready, send me into Blackrock Depths!
```

Map data:
```
Wailing Caverns - 11 0.22880709171295 0.82421052455902
Deadmines - 52 0.41420537233353 0.71216750144958
Gnomeregan - 30 0.31936836242676 0.71697419881821
Stratholme - 23 0.43229520320892 0.19960182905197
Blackrock Depths - 35 0.33528411388397 0.23898845911026
```

**Comment by p3lim** [comment]
Please give it a whirl: https://github.com/p3lim-wow/InteractiveWormholes/suites/9279150129/artifacts/434891003

**Comment by Taizunz** [comment]
Works great! 
Thanks for the quick turnaround on this request
