### ISSUE TITLE
error when opening the maw's Animaflow Teleporter

### ISSUE THREAD

**Issue by Loreinator** [p3lim-wow/InteractiveWormholes#47]
**Describe the bug**
When clicking on the Animaflow Teleporter, the following error appears:

Message: Interface/AddOns/InteractiveWormholes/addon.lua:20: bad argument #1 to '(for generator)' (table expected, got nil)
Time: Sun Jan  1 16:05:45 2023
Count: 1
Stack: Interface/AddOns/InteractiveWormholes/addon.lua:20: bad argument #1 to '(for generator)' (table expected, got nil)
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `(for generator)'
[string "@Interface/AddOns/InteractiveWormholes/addon.lua"]:20: in function `ShowMap'
[string "@Interface/AddOns/InteractiveWormholes/addon.lua"]:152: in function `HandleGossip'
[string "@Interface/AddOns/InteractiveWormholes/addon.lua"]:177: in function `callback'
[string "@Interface/AddOns/InteractiveWormholes/libs/Dashi/modules/event.lua"]:78: in function `TriggerEvent'
[string "@Interface/AddOns/InteractiveWormholes/libs/Dashi/modules/event.lua"]:87: in function <...ns/InteractiveWormholes/libs/Dashi/modules/event.lua:86>

Locals: 

**How to reproduce**
Go click on the Animaflow Teleporter with NPC id: 172925, at 48.28 41.45 in the maw.

**What did you expect?**
No errors to appear

**Comment by p3lim** [comment]
Already fixed in https://github.com/p3lim-wow/InteractiveWormholes/commit/a02e5ea96aea995f98dd4585df0b92641f989f5a, feel free to try out the alpha build found at the bottom here: https://github.com/p3lim-wow/InteractiveWormholes/actions/runs/3660133630
