### ISSUE TITLE
Legion Warrior class mount questline

### ISSUE THREAD

**Issue by fraenhawk** [p3lim-wow/InteractiveWormholes#51]
Good afternoon, progressing through warrior quests and ran into another issue. For the class mount I get the following in chat:
![image](https://user-images.githubusercontent.com/23088503/225116220-090ee75e-9da3-44fc-8232-db14b5d77ccb.png)

**Comment by p3lim** [comment]
I'll keep this issue open until you've finished the campaign :D
Let me know so I can add them all.

**Comment by p3lim** [comment]
Do you happen to remember which quests in the campaign you were doing for each of those? Would help with figuring out the location it should point to on the map.

**Comment by fraenhawk** [comment]
I'm done the class and mount quests and it was just those two. I believe the first is: https://www.wowhead.com/quest=44849/recruitment-drive
and the 2nd was: https://www.wowhead.com/quest=44889/resource-management
