### ISSUE TITLE
New zone to be added

### ISSUE THREAD

**Issue by Saxayone** [p3lim-wow/InteractiveWormholes#55]
There is a new zone that has a wormhole selection available that isn't added yet.

Tried to added it myself but didn't seem to work (maybe since it's own it's own map?)

This is what I had though:
data[109715] = { -- "Flip the portal horizontally and dive into it."
	mapID = 2133,
	x = 0.85,
	y = 0.8,
	tooltipMap = 2133,
}

Edit, ah it put it on the map for the new zone.

**Comment by p3lim** [comment]
100100.36 was released 3 hours before you opened this issue, please update.

**Comment by p3lim** [comment]
I thought I pushed an update for this but because of the GitHub outage today it must have failed.
