### ISSUE TITLE
Addon misidentifies dialogue options from Immersion addon as teleport destinations

### ISSUE THREAD

**Issue by Rauvagol** [p3lim-wow/InteractiveWormholes#56]
When using the immersion addon, dialogue choices are identified by this addon as teleport destinations, leading to an error message and the map opening.

![image](https://github.com/p3lim-wow/InteractiveWormholes/assets/7938335/734319a3-12d5-4ea8-aa6e-d0264185841d)

**Comment by p3lim** [comment]
That is odd, I'll have to test that.

**Comment by Rauvagol** [comment]
the weirdest part is it seemed to only happen some time after a reload, I
turned Immerson off, reloaded ui, it worked fine, then re-enabled
immersion, reloaded, and it worked fine.... until a while later when I
started getting the same error again

**Comment by p3lim** [comment]
Been using Immersion for a few days to try and replicate this issue, even did the entire Shadowmoon Valley campagin again as you did, and everything seemed to work just fine.

It might be a caching issue, so I'm adding a check just in case.
