### ISSUE TITLE
10.2 Dream Patch wormhole

### ISSUE THREAD

**Issue by F0resight** [p3lim-wow/InteractiveWormholes#61]
**Describe the solution you'd like**
The new zone has a wormhole option which would be nice to have added 

**Describe alternatives you've considered**
I've had to disable the addon to use it currently, which is a shame

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/InteractiveWormholes/commit/abd09df8ecbdca17356061cb963912f89728f636
