### ISSUE TITLE
Opening a portal does not open the corresponding zone map

### ISSUE THREAD

**Issue by cbossaers** [p3lim-wow/InteractiveWormholes#72]
**Describe the bug**
Opening a portal does not open the map of the zone, instead opening the map normally (current zone). i.e. if I'm in Valdrakken and use the Shadowlands wormhole, the map will open in Valdrakken, not showing the Shadowlands map. I have checked with friends and they have the same problem. This used to work pre TWW though.

**How to reproduce**
No particular steps. With no other addon enabled, all of TWW versions 110000.43/110000.44/1100000.45 present this error.

**What did you expect?**
For the map of the zone of the wormhole to open

**Screenshots**
(When uploading the video, the part where the addons are disabled is skipped for some reason, here's the link to streamable in case there's any doubts https://streamable.com/2xve19)
https://github.com/user-attachments/assets/3bb321e9-8133-4324-8840-7063ecb9acc7

**Comment by p3lim** [comment]
You can enable ths in the settings, it was disabled by default because it causes taint (e.g. eventually it'll break your action bars). There's nothing I can do about this, Blizzard needs to fix their map.

**Comment by cbossaers** [comment]
If the option is enabled I get a lua error, so I'm afraid that doesnt' work either. Could you share some info as to what specifically is the cause of the issue?

**Comment by p3lim** [comment]
I'll take a look at the option later, but it's low prio because it's inherently broken and unfixable.

**Comment by p3lim** [comment]
This will finally be fixed in 11.1.5, they added a safe way to open a specific map!
