### ISSUE TITLE
Lua error caused by InteractiveWormholes and BetterWorldQuests using same mapScale and zoomFactor setting names

### ISSUE THREAD

**Issue by justinkb** [p3lim-wow/InteractiveWormholes#74]
I worked around it by renaming mapScale, zoomFactor in IW to iwMapScale, iwZoomFactor, but there should probably be a better fix

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/Dashi/commit/5e046071edbe745ee4b67699e125684e1371b7ef
