### ISSUE TITLE
Stormsong Valley don't have teleport active on RU localization

### ISSUE THREAD

**Issue by Isegar** [p3lim-wow/InteractiveWormholes#8]
![2018-10-28-13-53-37](https://user-images.githubusercontent.com/9050806/49863193-cef69b00-fe10-11e8-9f1d-47b07924205a.png)

All quests are completed and bases are built.

**Comment by Isegar** [comment]
Got this output:

Dump: value=LibStub('HereBeDragons-2.0'):GetLocalizedMap(942)
[1]="Долина Штормов"

**Comment by p3lim** [comment]
I'm unsure what's causing this, I'll take a closer look this weekend.

**Comment by p3lim** [comment]
@Isegar Would you mind trying out the latest version from GitHub?

**Comment by Isegar** [comment]
![2019-01-13_22-13-29](https://user-images.githubusercontent.com/9050806/51089579-a26fcf00-1780-11e9-95b0-386a617ab707.png)

Overwrited all files in folder by GitHub files. And to be sure disabled all other addons. Unfortunately point still not there.

**Comment by p3lim** [comment]
Can you hold your shift key when interacting with the ship NPC and make sure you have actually unlocked the foothold? This seems _very_ odd to me.

**Comment by Isegar** [comment]
![2019-01-13_22-57-13](https://user-images.githubusercontent.com/9050806/51090010-c9c99a80-1786-11e9-902e-b78d04642c90.png)

With shift i have default interface window and 3 teleport points with Stormsong Valley included. It's in the middle and writed from lower letter, maybe it's the problem we are trying to find?

**Comment by p3lim** [comment]
Try that.

**Comment by Isegar** [comment]
It's strange, but still nothing appears. And with shift it is there.

**Comment by p3lim** [comment]
Compare these two (with the window open):
```
/dump LibStub('HereBeDragons-2.0'):GetLocalizedMap(942)
/dump (select(3,GetGossipOptions()))
/dump (select(3,GetGossipOptions())):lower():match(LibStub('HereBeDragons-2.0'):GetLocalizedMap(942):lower())
```

**Comment by Isegar** [comment]
Dump: value=LibStub('HereBeDragons-2.0'):GetLocalizedMap(942):lower()
[1]="долина штормов"

Dump: value=(select(3,GetGossipOptions())):lower()
[1]="отправляемся в долину штормов."

Dump: value=(select(3,GetGossipOptions())):lower():match(LibStub('HereBeDragons-2.0'):GetLocalizedMap(942):lower())
empty result

**Comment by Isegar** [comment]
![2019-01-14_12-49-40](https://user-images.githubusercontent.com/9050806/51105777-fc14df80-17fa-11e9-89bc-0f9ea7632a80.png)

Thankyou very much. Stormsong Valley now have teleport.
